### PR TITLE
Child form langauage update & other fix

### PR DESCRIPTION
**Pull request by salihkiraz**
Child form langauage update
radibox , checkbox fix error
general langauage imporovent

### CODE REVIEW

**Comment by salihkiraz** [comment]
Why does it take a long time to approve?

**Comment by fherryfherry** [comment]
have you check my last review ?

**Comment by salihkiraz** [comment]
yes. no error. No conflict.

**Comment by fherryfherry** [comment]
Don't make it a habit of using translation without crudbooster prefix

**Comment by fherryfherry** [comment]
Don't forget to re-pull from the master, I've do update. thanks

**Pull request closed without merging**
