### PR TITLE
Validation Unique NULL Issue Fix

### PR DESCRIPTION
**Pull request by tomatoe45**
Remove the '&' before the $validationItem in line 794 from CBController

### CODE REVIEW

**Comment by fherryfherry** [comment]
Do not remove & from $validationItem , why we use & is for override the current $validationItem value

**Comment by tomatoe45** [comment]
I see.. it seems like a bug in validation process..

 [#490](https://github.com/crocodic-studio/crudbooster/issues/490)

**Comment by fherryfherry** [comment]
please try

**Comment by tomatoe45** [comment]
There you go.. thanks @fherryfherry..

**Pull request merged**
