### PR TITLE
Fix Read-Only in Date Component

### PR DESCRIPTION
**Pull request by elevationeg**
Previous Code was forcing to be read-only always. This change will make the date input read-only or not depending on the property 'readonly' as it was designed.

### CODE REVIEW

**Comment by fherryfherry** [comment]
it prevents us to enter the alpha character, it's why I put readonly on it

**Comment by elevationeg** [comment]
Thank you for your the fast reply. Looking the documentation, the date component has a property **readyonly**. I think you should make it flexible and let the developers have the option. I have some frontend (with jQuery) and backend (before edit/add hook) validation, so I am not worry about what the final user inputed. I never trust them.

Following your thinking, I can remove the read-only property by inspecting the HTML, and it can still inputing alpha characters.

I think, if this is OK with you, I can change the code so, by default, it will be read-only but if the developer wants to change it to be writable, he/she need to set the property **readyonly** as **false**

So the code will look like:

`@if(!isset($override) || $override) readonly @endif`

What are your thoughts? Thank you so much fir taking the time to look at it

**Comment by catfishseo** [comment]
Any thought?

**Comment by fherryfherry** [comment]
Hi some user especially client don't want to see that date input may enter alpha characters, so it's better the date input may not enter alpha characters, as I know datepicker plugin can prevent this, but last I checked, it can enter alpha chars, maybe I miss something for datepicker plugin, it's way for temporary solution, I put readonly on it

**Comment by fherryfherry** [comment]
what is your thought? @elevationeg

**Comment by elevationeg** [comment]
**OPTION 1.**
Like I said before 

> I can change the code so, by default, it will be readonly but if the developer wants to change it to be writable, he/she need to set the property readyonly as false.
> So the code will look like:
> `@if(!isset($override) || $override) readonly @endif`

**OPTION 2.**
Remove readonly and have this jquery:
```
    $("#slector").bind("keypress", function(event) { 
        var charCode = event.which;
        if (charCode <= 13) return true; 

        var keyChar = String.fromCharCode(charCode); 
        return /[0-9\/]/.test(keyChar); 
    });
```

**OPTION 3.**
Since I do frontend (js) and server side validation (php), I just removed the **readonly** using jquery:
`$("#selector").attr("readonly", false);`

**Pull request merged**
