### PR TITLE
javascript fancybox v3.0 update 

### PR DESCRIPTION
**Pull request by salihkiraz**
javascript fancybox v3.0 update

### CODE REVIEW

**Comment by fherryfherry** [comment]
image
what do you think about this license? Is it safe?

**Comment by salihkiraz** [comment]
"fancyBox is licensed under the GPLv3 license for **all open source applications.** "

crudbooster open source application .
GPLv3 license and free 👍

**Comment by franciscoluiz** [comment]
@salihkiraz Ok, but that restricts the crudbooster to being used only in opensource projects. No one can use crudbooster if the project is commercial (paid). (What the MIT license contemplates)

**Comment by fherryfherry** [comment]
@franciscoluiz it was there in my mind

**Comment by salihkiraz** [comment]
ok. 
altervative 
http://lokeshdhakar.com/projects/lightbox2/#license .
I will update.

**Pull request closed without merging**
