### PR TITLE
Master update

### PR DESCRIPTION
**Pull request by davodavodavo3**
Beta changes
Changes:
- Code style.
- Base path of CB chaged to uppercase like Crocodicstudio\Crudbooster\
- Userfiles moved to publishable folder like database, lang,assets.
- Controllers and Middleware moved to Http  folder
- All this configured that CrudBooster can be installed and updated well

@fherryfherry will be nice if you integrate CodeClimate or other code analizing tool
CodeClimate response
codeclimate — 13358 new issues (10315 fixed) for beta branch

### CODE REVIEW

**Comment by davodavodavo3** [comment]
Im here @fherryfherry for any questions.

**Comment by fherryfherry** [comment]
Is it all? I want to try

**Comment by davodavodavo3** [comment]
Yes you can try, but this is not all, this is only path reconstruction and all that i have writen up

**Comment by davodavodavo3** [comment]
Can you add CodeClimate? Do you know for what is it?

**Comment by fherryfherry** [comment]
I've no experience with it, but I will to try add

**Comment by davodavodavo3** [comment]
Its not complicated

**Comment by davodavodavo3** [comment]
Sign in with your GitHub account
https://codeclimate.com/

**Comment by davodavodavo3** [comment]
Know for crudbooster it show like this
https://github.com/davodavodavo3/crudbooster/pull/5

**Comment by davodavodavo3** [comment]
Write when you install it

**Comment by fherryfherry** [comment]
I've added this repo into codeclimate dashboard, then should I integrate codeclimate at the GitHub setting as well?

**Comment by davodavodavo3** [comment]
Go to repo settings click Integrations & services
then Add service CodeClimat and see steps for integration

**Comment by davodavodavo3** [comment]
Do you install beta version of CB? All works fine?

**Comment by fherryfherry** [comment]
i got this 
image

**Comment by davodavodavo3** [comment]
hmm, in the config/app do you set service provider with upercase
like this Crocodicstudio\Crudbooster\CRUDBoosterServiceProvider::class,

**Comment by fherryfherry** [comment]
Ohh I really forget about that 😄 ,

**Comment by davodavodavo3** [comment]
@fherryfherry  is there way to display user name in text field, when field value is user id?

**Comment by fherryfherry** [comment]
Ofcourse by using callback php for now

Bytheway today i want to commit many changes in beta
Pada tanggal 28 Apr 2017 08.17, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
What kind of changes you will do?

**Comment by fherryfherry** [comment]
Installation
Variable and properties naming camelCase
Method name camelCase
Callback
Table and column naming
Manymore
But for css, js like yours I didn't change yet
Pada tanggal 28 Apr 2017 09.31, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
Super, let me know when you do that upgrade)))))

**Comment by davodavodavo3** [comment]
@fherryfherry  dont forget to Laravel user table insted of CB cms_usert table, for next i will do authorization with that table and will create CB own Authentification Controller

**Comment by fherryfherry** [comment]
Ahh yes, would you tell me where I should start from to integrate with Lara Auth, or maybe next you want to help me to change it

**Comment by davodavodavo3** [comment]
I will do that , you will need only to remove cms_users.
On CB install , update command dont remove default Laravel migration of users table,
Create new publishable migration with role column
(cms_privileges need to renamed to cms_roles and cms_privileges_roles to cms_permission_roles) 
 and status column.

**Comment by davodavodavo3** [comment]
For next there must be functionality  to assign default role on registration for default Laravel registration

**Comment by davodavodavo3** [comment]
In CB config add
`"add_user_role_on_register" => "user"` //Name of Role to asign on user (this will add Id of Role User to user table)

Remove all UPERCASE configurations , make them snake like all config files.

Add this in CB Service Provider
```
if (config('crudbooster.add_user_role_on_register')) {
            $app_user = config('auth.providers.users.model');
            $app_user::created(function ($user) {
                if (is_null($user->role_id)) {

                    \\Update sql or eloquent for update user model and add role
                }
            });
        }
```

**Comment by davodavodavo3** [comment]
Why you chose AdminLTE theme?
Check opensource themes if you want we can change to more styled and crretive theme
https://speckyboy.com/free-bootstrap-admin-themes/

**Comment by fherryfherry** [comment]
AdminLTE is quite familiar

**Comment by davodavodavo3** [comment]
But for any, look at there, maybe you will like something.

**Comment by fherryfherry** [comment]
maybe in the future CB has a function to change admin layout/template but not for at this time

**Comment by davodavodavo3** [comment]
Realy, super.

**Comment by franciscoluiz** [comment]
The option to choose the theme, I think is wonderful.

I do not know you, @davodavodavo3, but I still think it would be even more wonderful if the theme supported ajax. (No matter what) #333

**Comment by davodavodavo3** [comment]
@fherryfherry hi how are you?
Is there any news about update?

**Comment by fherryfherry** [comment]
yes I've updated today, But there is still much to improve

**Comment by davodavodavo3** [comment]
is there need to use middleware'=>['web] in routes?

**Comment by fherryfherry** [comment]
Check the routes file
Pada tanggal 2 Mei 2017 21.26, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
I want to say that there is no need to use middleware'=>['web] in routes since  Laravel 5.2.27.
Out of the box, the web middleware group is automatically applied to your  routes/web.php file by the RouteServiceProvider.

**Comment by fherryfherry** [comment]
Ohh okay, thx for info
Pada tanggal 2 Mei 2017 22.45, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
@fherryfherry hi. Do you have any changes in beta . I want to implement authorization with laravel auth

**Comment by fherryfherry** [comment]
no, you can commit

**Comment by davodavodavo3** [comment]
@fherryfherry there is no way to use db prefix , im right?

**Comment by fherryfherry** [comment]
Sorry what do you mean?  :D
Pada tanggal 3 Mei 2017 23.27, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
i add prefix in database tables , and now i have table like PREFIX_cms_privilegies and this doesnt work.

**Comment by fherryfherry** [comment]
You mean didn't work on?
Pada tanggal 3 Mei 2017 23.36, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
yes, it does not work, in CB you don use eloquent right? You use Database builder , and for that you need to get databse prefix with DB::getTablePrefix() method

**Comment by fherryfherry** [comment]
Ouwm, i've never tried before to using db prefix, usually i use prefix in
the table name,and did not facing issue
Pada tanggal 3 Mei 2017 23.39, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
need to be fixed, now im loking for solution

**Comment by davodavodavo3** [comment]
@fherryfherry there is error in filemanager unisharp they change their code

**Comment by fherryfherry** [comment]
Actually I want to make a filemanager instead of thirdparty file manager,
Pada tanggal 4 Mei 2017 04.14, "Scorpion" <notifications@github.com>
menulis:

**Comment by davodavodavo3** [comment]
@fherryfherry leave alone for now file manager only fix it to work with new version. 
And will be nice if you fix issues in beta branch.I want to implement auth and other futures that CB need.

**Comment by davodavodavo3** [comment]
@fherryfherry write me please when you will fix beta branch

**Comment by davodavodavo3** [comment]
@fherryfherry is there way to add multilang switcher to add content in many languages on edit?

**Pull request merged**
