### PR TITLE
Update CBController.php Direct Reference to ID for PHP 7

### PR DESCRIPTION
**Pull request by tiznull**
Had an issue with Child Forms do not pickup the ID of the foreign KEY after insertion. The logic helps pickup the right ID under the user interaction.

### CODE REVIEW

**Comment by marcq64** [comment]
@tiznull

Had the same issue and could fix it thanks to you. Thank you.

Did you had also problem by saving several rows|records with master detail child form ? 

I'm suddenly unable to save more than one row|record in detail table resulting in

SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 2

Crudbooster didn't pass empty element values.

**Comment by tiznull** [comment]
@marcq64 - I am having the same issue. For me it happens under a unique case of **add->save->edit item + add new item + add another item->save**.

If you look at the SQL statement you will see the second "set" is exploded, but not into insertable sets.

`(col1, col2 col3), (col1,col2,col3,col1,col2,col3)`

I am working through that error. I will let you know if I figure it out.

**Comment by marcq64** [comment]
@tiznull thanks a lot for your information. 

For me it happens when I add new items, one after another and want to save it. 

Yes I had a look a the SQL statement and I saw it.

I just thought they would fix this error which concerns an important asset of Crudbooster until beta version 6 is ready to use with among other master child CRUDs...

Would be great if you could ping me about your findings, since I'm already overloaded with other issues.

Cheers, Marc

**Comment by tiznull** [comment]
I am submitting a fix for the problem here:
https://github.com/crocodic-studio/crudbooster/pull/1525

**Comment by marcq64** [comment]
@tiznull Thanks a lot I will test it tomorrow, cheers

**Pull request merged**
