### PR TITLE
CrudBooster NeedForSpeed

### PR DESCRIPTION
**Pull request by davodavodavo3**
All Java javascript files are attached before body tag.
Only css files are included in header.

### Adeed stack functionality in admin_template_blade for including user css files from own blade files

@stack('css')

### Adeed stack functionality in admin_template_blade for including user js files from own blade files

@stack('javascript')

### Fixed some missing tags in templates like form tag and other.
I cant resolve only one thing! Google Maps form type, because i work on local and i dont have a Google API key(googlemap type component js,css files need to be included in their places footer and header).

And I recommend to download  those libraries that are from cdn or other hostings for using them without internet connection(today my internet die) and change to CDN when project will be for production.

# NOW CB IS MORE BOOSTED )))

### CODE REVIEW

**Comment by fherryfherry** [comment]
I think your local repo need to update before commit, I found much differents with the latest version

**Comment by davodavodavo3** [comment]
Hi fherryfherry ,Realy, hmmm i will check

**Comment by davodavodavo3** [comment]
Can you tell in a few words what caind of changes are there?

**Comment by catfishseo** [comment]
+1

**Comment by fherryfherry** [comment]
Please update to the master, there is a conflict at src/views/sidebar.blade.php

and, have you fixing my review?

**Comment by fherryfherry** [comment]
would you continue this PR? @davodavodavo3

**Comment by catfishseo** [comment]
@fherryfherry

**Comment by catfishseo** [comment]
@fherryfherry @davodavodavo3 if you need some help/ code review it, please let me know. I would love to see this merged into master

**Comment by davodavodavo3** [comment]
oh i dont see comments guys , no i not , im closing it for now , i will do it later

**Pull request closed without merging**
