### PR TITLE
fix minor, bug when doing graded chain select

### PR DESCRIPTION
**Pull request by furqon**
add ampersand colon

### CODE REVIEW

**Comment by fherryfherry** [comment]
This PR is for CB 5.4.0 or master?

**Comment by jdredondo** [comment]
this bug has already been fixed in v.5.4.0

**Comment by furqon** [comment]
this occured in master, 
just showed that it already fixed in 5.4

**Comment by fherryfherry** [comment]
hi @furqon please resolve conflicts, thanks

**Comment by furqon** [comment]
done

**Pull request merged**
