### PR TITLE
The most obvious possible refactors

### PR DESCRIPTION
**Pull request by imanghafoori1**
This code can be much better than it is now
I have started with the most obvious ways

### CODE REVIEW

**Comment by imanghafoori1** [comment]
These commits bring no new feature neither fixes any bugs.
Only refactoring to reach simpler and more maintainable code-base.
Hopefully I introduce no new bugs along the way.

**Comment by imanghafoori1** [comment]
@fherryfherry 
Hi,
Please declare how happy you are with my work. and let me know whether you are going to merging it or not.

**Comment by imanghafoori1** [comment]
Most of the refactorings follow this simple yet very effecting rule:

https://stackoverflow.com/questions/36707/should-a-function-have-only-one-return-statement

**Comment by fherryfherry** [comment]
Thank you great and nice work iman...

Pada tanggal 31 Agt 2017 13.53, "Iman" <notifications@github.com> menulis:

Most of the refactorings follow this simple yet very effecting rule:

https://stackoverflow.com/questions/36707/should-a-
function-have-only-one-return-statement

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/crocodic-studio/crudbooster/pull/783#issuecomment-326207023>,
or mute the thread

**Comment by abenzakour** [comment]
In name of the community,  I want to thank you too for this great interesting that you give to crudbooster.

**Comment by imanghafoori1** [comment]
I would like to continue working on this project...

**Comment by imanghafoori1** [comment]
@fherryfherry 
Are you ok with adding an open source package and refactor the code using that?
github.com/imanghafoori1/laravel-widgetize

**Comment by imanghafoori1** [comment]
Currently the project has a lot of php code in the blade files, which can be nicely extracted into dedicated classes with the help of widgetize package. Let me know if you are ok with using another open source package as a dependency...
@fherryfherry

**Comment by fherryfherry** [comment]
I thought you may split into new Pull Request for the blade case

Pada tanggal 2 Sep 2017 02.20, "Iman" <notifications@github.com> menulis:

**Pull request merged**
