### PR TITLE
all authority is not recorded when it is not selected

### PR DESCRIPTION
**Pull request by salihkiraz**
ekran alintisi

### CODE REVIEW

**Comment by fherryfherry** [comment]
hi, @salihkiraz which version do you use? master or 5.4.* (a.k.a live version) ?

**Comment by salihkiraz** [comment]
@fherryfherry  5.4

**Comment by fherryfherry** [comment]
can you resolve the conflict? @salihkiraz

**Comment by salihkiraz** [comment]
yes. see commits.

**Comment by fherryfherry** [comment]
Please re-pull  @salihkiraz

**Pull request closed without merging**
