### PR TITLE
Module generator Table condition options add

### PR DESCRIPTION
**Pull request by salihkiraz**
image

### CODE REVIEW

**Comment by davodavodavo3** [comment]
@salihkiraz what is the difference between hook_query_index method and this new functionality?

**Comment by fherryfherry** [comment]
In my experience, it might cause confuse where the SQL condition placed, so we can use hook_query_index instead of it

**Comment by salihkiraz** [comment]
This method works when doing the insert operation.
Hook_query_index does not work on insert.

**Comment by davodavodavo3** [comment]
There is many hook's that can be used for inserting.
Before_edit the table after edit table, when inserting something in table.
Maybe we did not understand something?

**Comment by salihkiraz** [comment]
ok.

**Pull request closed without merging**
