### PR TITLE
Add pre-checking for some custom validation if needed before execute API

### PR DESCRIPTION
**Pull request by furqon**
This is tend to add custom pre-checking/validation before executing API if needed.
If checking not pass then set 
`$this->discard_api = true;`
and send the message
`$this->hook_api_message = 'Some message why not pass!';`

### CODE REVIEW

**Comment by fherryfherry** [comment]
Hi it's better to be hook_validate(), instead of hook_discard_api() , because the purpose is for pre-checking / validating the API @furqon

**Comment by furqon** [comment]
name altered..

**Comment by fherryfherry** [comment]
@furqon check my last review

**Comment by furqon** [comment]
i'm sorry I dont get what you mean :)
I thought only alter the name..

**Pull request merged**
