### PR TITLE
To avoid loss of parameters per url when applying a filter

### PR DESCRIPTION
**Pull request by jdredondo**
To avoid loss of parameters per url when applying a filter

### CODE REVIEW

**Comment by fherryfherry** [comment]
@jdredondo I'm afraid it will cause duplicate URL params if you don't select what params that should be in input[type=hidden], may be only param q, and param limit that should be kept, isn't it?

**Comment by jdredondo** [comment]
I have several modules in which I send parameters by url and then filter with the hook_query_index method, but when applying a filter these parameters are lost, I will except the parameters "limit" and "q" with
`foreach ($parameters as $key => $value) {
	if($key != 'limit' and $key != 'q') {
		echo "<input type='hidden' name='".$key."' value='".$value."'>";
	}
}`

**Comment by jdredondo** [comment]
Hello @fherryfherry, I noticed that the parameters 'q' and 'limit' are also lost when applying a filter, so the first solution helps to keep them, I have corrected again.

**Comment by jdredondo** [comment]
I will rethink this solution, since after several tests I have found some issues

**Pull request closed without merging**
