### PR TITLE
radio , checkbox dataquery ,datatable supoort added  | image view lig…

### PR DESCRIPTION
**Pull request by salihkiraz**
radio , checkbox dataquery ,datatable supoort added 
image view lightbox update

### CODE REVIEW

**Comment by franciscoluiz** [comment]
Please, @salihkiraz, can you show a screenshot about this?

**Comment by salihkiraz** [comment]
module genetor -> form -> radio | checkbox -> options

image

preview - dataquery data
image

lightbox puligns - remove fancybox - ligtbox is MIT licence.
image

**Comment by fherryfherry** [comment]
btw can you complete the documentation about this PR ? @salihkiraz

**Comment by salihkiraz** [comment]
ok. I will update.

**Pull request merged**
