### PR TITLE
Fix: Target class [CBSeeder] does not exist.

### PR DESCRIPTION
**Pull request by dedyksuntoro**
Comment or remove line `namespace Database\Seeders;`

### CODE REVIEW

**Comment by fherryfherry** [comment]
di versi terbaru kelihatanya sudah saya fixing mas

**Comment by dedyksuntoro** [comment]
Iya mas, tapi waktu fresh install dengan laravel 7 keatas masih mengalami CBSeeder not exist. Setelah coba hapus line tersebut bisa mas, kondisi fresh install.

**Comment by retinqdevelopment** [comment]
I have a new installation of laravel 8 and crudbooster, but this error still exist.

**Comment by FullStuckDeveloper** [comment]
> I have a new installation of laravel 8 and crudbooster, but this error still exist.

I found same trouble, and try to uncomment namespace Database\Seeders, it works.

dsdsa

**Pull request merged**
