### PR TITLE
Submodule Custom parent id support

### PR DESCRIPTION
**Pull request by salihkiraz**
sample 
`$this->sub_module[] = ['label'=>'Değişkenler','path'=>'app_variables','parent_columns'=>'code','custom_parent_id'=>'code','foreign_key'=>'master_code','button_color'=>'info','button_icon'=>'fa fa-bars','showIf'=>"[master_code] == '999'"];`

### CODE REVIEW

**Comment by fherryfherry** [comment]
before I merge this pull, please also create documentation

**Comment by salihkiraz** [comment]
hello, I updated.

**Comment by fherryfherry** [comment]
Oke 👌
Pada tanggal 19 Mei 2017 22:37, "Salih KİRAZ" <notifications@github.com>
menulis:

**Comment by salihkiraz** [comment]
??

**Pull request merged**
